version: '3.8'

services:
  # Serviço da API NestJS
  api:
    build: .
    ports:
      - "8003:3000"
    volumes:
      - ./prisma:/app/prisma
      - ./dist:/app/dist
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
    depends_on:
      - db

      
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
