version: "3.9"
services:
  course-api:
    build: .
    ports:
      - "8002:3000"
    volumes:
      - ./src/:/usr/src/app/src/
    depends_on:
      - course-db
  course-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_db
    ports:
      - "3308:3306"
    volumes:
      - course-db-data:/var/lib/mysql

volumes:
  course-db-data:
