version: "3.9"
services:
  web:
    build: .
    container_name: html-server
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
